version: '2'

services:

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    hostname: logstash
    user: root
    ports:
      - "5044:5044"
    expose:
      - "5044"
    volumes:
      - ../logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ../logstash/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    user: root
    depends_on:
      - logstash
    volumes:
      - ../filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/data/qmul:/root/logs/qmul
      - /home/data/durham:/root/logs/durham
      - /home/data/scarf:/root/logs/scarf
      - /home/data/cloud:/root/logs/cloud
      - /home/data/ic_t2:/root/logs/ic_t2
      - /home/data/cambridge:/root/logs/cambridge
